# -*- coding: utf-8 -*-
"""series.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CfYtXu63XYB-3eQHIhnCKRnmZ47UUPBf
"""

import pandas as pd



"""#series"""

import pandas as pd

s1=pd.Series([4,7,-5,3])

s1

s1=pd.Series([4,7,-5,3],index=['d','b','c','a'])

s1

s1.index=['a','b','c','d']

s1

s1['d']

s1['b']

s1['c']

s1['c']=-10

s1

s1[['a','d']]=6,7

s1

s1['a','b']=10,20

s1

s1['a':'d']

s1[s1>0]

s1

s1*2

s1*3

s1['a']*2

s1[s1>10]

s1%2

s1/2

dict={'ohio':17000,'oregon':18000,'texas':19000,'california':20000}

dict

s2=pd.Series(dict)

s2

s2.index

s2.values

s2.index=['atlanta','oregon','texas','california']

s2

s2=pd.Series(dict,index=['ohio','oregon','texas','california'])

s2

a=pd.Series(6)

a

type(a)

type(a[0])

s2

s2=pd.Series(dict,index=['atlanta','oregon','texas','california'])

s2

s2.name='population'

s2

s2.index.name='states'

s2

s1=pd.Series(12,index=[4,6,8])

s1

s3=pd.Series(['a','e','i','o','u'])

s3

s3.index.name='vowels'

s3

s3.index=(['a','e','i','o','u'])

s3

import pandas as pd
s7=pd.Series([6,7,-10,7])

s7/2

import numpy as np

import pandas as pd

s7=pd.Series([4,7,-5,3])

np.exp(s7)

